version: "3.7"

services:
  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - '8086:8086'
    restart: always
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=sesores
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user
    
  driver:
    build:
      context: ./DRIVER
    restart: always
    depends_on:
      - influxdb

  chronograf:
    image: chronograf:1.8.4-alpine
    ports:
      - 8888:8888
    restart: always
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:7.0.0
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  # grafana-storage:
  influxdb-storage:
  chronograf-storage:


#  To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
#  Si se hace cambios en el driver